name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update and Restart HTTPD
      run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.INSTANCE_PUBLIC_IP }} << 'EOF'
            cd /var/www/html/LoudBalanceApp-1
            git config --global --add safe.directory /var/www/html/LoudBalanceApp-1
            git pull origin main
            sudo cp index.html /var/www/html/index.html
            sudo systemctl restart httpd
          EOF